language: ruby
script: 'bundle exec rake test:coverage --trace'
install:
  - bundle install --retry=3
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.2

matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="--2.0"
    - rvm: jruby-head
      env: JRUBY_OPTS="--2.1"
  allow_failures:
    - rvm: jruby-head
    - rbx-2
